<?php

use App\Http\Controllers\Api\V1\ApprovalController;
use App\Http\Controllers\Api\V1\AppUpdateController;
use App\Http\Controllers\Api\V1\AttachmentController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CrossBranchDashboardController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\DeliveryNoteController;
use App\Http\Controllers\Api\V1\ImportantFileController;
use App\Http\Controllers\Api\V1\JourneyController;
use App\Http\Controllers\Api\V1\MasterController;
use App\Http\Controllers\Api\V1\MeetingController;
use App\Http\Controllers\Api\V1\MonitoringController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OutletTransactionController;
use App\Http\Controllers\Api\V1\OutletRequestController;
use App\Http\Controllers\Api\V1\ReceivableController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\PromotionControlController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\RouteEstimateController;
use App\Http\Controllers\Api\V1\RouteMasterController;
use App\Http\Controllers\Api\V1\ShipToLocationController;
use App\Http\Controllers\Api\V1\SyncStateController;
use App\Http\Controllers\Api\V1\UserDeviceController;
use App\Http\Controllers\Api\V1\VisitActivityController;
use App\Http\Controllers\Api\V1\VisitController;
use App\Services\IdempotencyService;
use App\Services\PromotionService;
use App\Services\SalesOrderCalculator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('v1/files/{importantFile}/download/signed/{user}', [ImportantFileController::class, 'signedDownload'])
    ->middleware('signed')
    ->name('files.signed-download');

Route::prefix('v1')->group(function () {
    Route::post('auth/login', [AuthController::class, 'login']);
    Route::post('auth/refresh', [AuthController::class, 'refresh']);
    Route::middleware('auth:sanctum')->group(function () {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('users/{user}/device-sessions', [UserDeviceController::class, 'sessions']);
        Route::put('users/{user}/max-devices', [UserDeviceController::class, 'updateLimit']);
        Route::get('app-updates/android/check', [AppUpdateController::class, 'checkAndroid']);
        Route::get('app-updates/android/{release}/download', [AppUpdateController::class, 'downloadAndroid']);
        Route::post('app-updates/android', [AppUpdateController::class, 'storeAndroid']);
        Route::post('attachments', [AttachmentController::class, 'store']);
        Route::get('attachments/{attachment}', [AttachmentController::class, 'show']);
        Route::get('attachments/{attachment}/content', [AttachmentController::class, 'content']);
        Route::get('master/products', [MasterController::class, 'products']);
        Route::get('master/products/{product}/image', [MasterController::class, 'productImage']);
        Route::get('master/promotions', [MasterController::class, 'promotions']);
        Route::get('promotions', [MasterController::class, 'promotions']);
        Route::get('promotions/dashboard', [PromotionControlController::class, 'dashboard']);
        Route::post('promotions/special-requests', [PromotionControlController::class, 'specialRequest']);
        Route::post('promotions/{promotion}/merchandising-proofs', [PromotionControlController::class, 'proofs']);
        Route::get('promotions/{promotion}', [MasterController::class, 'promotion']);
        Route::get('files', [ImportantFileController::class, 'index']);
        Route::post('files', [ImportantFileController::class, 'store']);
        Route::post('files/{importantFile}/download', [ImportantFileController::class, 'downloadUrl']);
        Route::get('master/outlets', [MasterController::class, 'outlets']);
        Route::get('master/ship-to-locations', [ShipToLocationController::class, 'index']);
        Route::post('outlets/{outlet}/ship-to-locations', [ShipToLocationController::class, 'store']);
        Route::post('outlets', [OutletRequestController::class, 'store']);
        Route::get('master/route-assignments', [RouteMasterController::class, 'index']);
        Route::get('master/route-sales', [RouteMasterController::class, 'sales']);
        Route::put('master/route-sales/{sales}/divisions', [RouteMasterController::class, 'updateSalesDivisions']);
        Route::put('master/outlets/{outlet}/divisions', [RouteMasterController::class, 'updateOutletDivisions']);
        Route::post('master/route-assignments/bulk', [RouteMasterController::class, 'storeBulk']);
        Route::post('master/route-assignments', [RouteMasterController::class, 'store']);
        Route::patch('master/route-assignments/{routeAssignment}', [RouteMasterController::class, 'update']);
        Route::delete('master/route-assignments/{routeAssignment}', [RouteMasterController::class, 'destroy']);
        Route::get('master/outlets/{outlet}/performance', [MasterController::class, 'performance']);
        Route::get('master/snapshot', [MasterController::class, 'snapshot']);
        Route::get('dashboard', [DashboardController::class, 'show']);
        Route::get('dashboard/branches', [CrossBranchDashboardController::class, 'show']);
        Route::post('monitoring/locations', [MonitoringController::class, 'recordLocation']);
        Route::get('monitoring/team', [MonitoringController::class, 'team']);
        Route::get('monitoring/activities', [MonitoringController::class, 'activities']);
        Route::get('monitoring/team/{sales}/locations', [MonitoringController::class, 'locationHistory']);
        Route::get('reports/transactions', [ReportController::class, 'transactions']);
        Route::get('reports/summary', [ReportController::class, 'summary']);
        Route::get('reports/archives', [ReportController::class, 'archives']);
        Route::get('reports/transactions/export.csv', [ReportController::class, 'exportCsv']);
        Route::get('reports/visits/export.csv', [ReportController::class, 'exportVisitsCsv']);
        Route::get('reports/transactions/export.pdf', [ReportController::class, 'exportPdf']);
        Route::get('visits', [VisitController::class, 'index']);
        Route::post('routes/estimate', [RouteEstimateController::class, 'estimate']);
        Route::get('outlets/{outlet}/visit-activities', [VisitActivityController::class, 'outletHistory']);
        Route::post('visits/check-in', [VisitController::class, 'checkIn']);
        Route::post('visits/check-out', [VisitController::class, 'checkOut']);
        Route::post('visits/defer', [VisitController::class, 'defer']);
        Route::post('visits/cancel', [VisitController::class, 'cancel']);
        Route::post('sales-orders', fn (Request $request, OutletTransactionController $controller, IdempotencyService $service, SalesOrderCalculator $calculator, PromotionService $promotions) => $controller->store($request, $service, $calculator, $promotions, 'sales_order'));
        Route::patch('sales-orders/{transaction}/status', [OutletTransactionController::class, 'changeSalesOrderStatus']);
        Route::get('sales-orders/{transaction}/receipt', [OutletTransactionController::class, 'receipt']);
        Route::get('sales-orders/{transaction}/receipt.pdf', [OutletTransactionController::class, 'receiptPdf']);
        Route::post('purchases', fn (Request $request, OutletTransactionController $controller, IdempotencyService $service, SalesOrderCalculator $calculator, PromotionService $promotions) => $controller->store($request, $service, $calculator, $promotions, 'purchase'));
        Route::post('returns', fn (Request $request, OutletTransactionController $controller, IdempotencyService $service, SalesOrderCalculator $calculator, PromotionService $promotions) => $controller->store($request, $service, $calculator, $promotions, 'return'));
        Route::post('supplier-returns', fn (Request $request, OutletTransactionController $controller, IdempotencyService $service, SalesOrderCalculator $calculator, PromotionService $promotions) => $controller->store($request, $service, $calculator, $promotions, 'supplier_return'));
        Route::post('gifts', fn (Request $request, OutletTransactionController $controller, IdempotencyService $service, SalesOrderCalculator $calculator, PromotionService $promotions) => $controller->store($request, $service, $calculator, $promotions, 'gift'));
        Route::post('outlet-notes', fn (Request $request, OutletTransactionController $controller, IdempotencyService $service, SalesOrderCalculator $calculator, PromotionService $promotions) => $controller->store($request, $service, $calculator, $promotions, 'note'));
        Route::get('outlets/{outlet}/transactions', [OutletTransactionController::class, 'history']);
        Route::get('outlets/{outlet}/receivables', [ReceivableController::class, 'index']);
        Route::post('receivables/{invoice}/payments', [ReceivableController::class, 'pay']);
        Route::get('outlets/{outlet}/payment-summary', [PaymentController::class, 'outletReceivables']);
        Route::get('payments/receivables-snapshot', [PaymentController::class, 'receivablesSnapshot']);
        Route::get('payments', [PaymentController::class, 'index']);
        Route::post('payments', [PaymentController::class, 'store']);
        Route::post('payments/{payment}/verify', [PaymentController::class, 'verify']);
        Route::post('collection-activities', [PaymentController::class, 'collectionActivity']);
        Route::get('journeys', [JourneyController::class, 'index']);
        Route::get('journeys/current', [JourneyController::class, 'current']);
        Route::post('journeys', [JourneyController::class, 'store']);
        Route::patch('journeys/{journey}/status', [JourneyController::class, 'status']);
        Route::post('journeys/{journey}/start', [JourneyController::class, 'start']);
        Route::post('journeys/{journey}/reset-visits', [JourneyController::class, 'resetVisits']);
        Route::get('delivery-notes', [DeliveryNoteController::class, 'index']);
        Route::post('delivery-notes', [DeliveryNoteController::class, 'store']);
        Route::post('delivery-notes/{deliveryNote}/submit', [DeliveryNoteController::class, 'submit']);
        Route::post('delivery-notes/{deliveryNote}/use', [DeliveryNoteController::class, 'use']);
        Route::post('delivery-notes/{deliveryNote}/cancel', [DeliveryNoteController::class, 'cancel']);
        Route::get('approvals', [ApprovalController::class, 'index']);
        Route::post('approvals/{approval}/decision', [ApprovalController::class, 'decide']);
        Route::get('meetings', [MeetingController::class, 'index']);
        Route::post('meetings', [MeetingController::class, 'store']);
        Route::post('meetings/join-by-code', [MeetingController::class, 'joinByCode']);
        Route::post('meetings/{meeting}/join', [MeetingController::class, 'join']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::post('notifications/devices', [NotificationController::class, 'registerDevice']);
        Route::delete('notifications/devices/{device}', [NotificationController::class, 'unregisterDevice']);
        Route::post('notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::get('sync/state', [SyncStateController::class, 'show']);
    });
});
